### ISSUE TITLE
domain has been added, not changed

### ISSUE THREAD

**Issue by umisora** [sorah/codily#1]
Codily is a best practice to manage fastly. Thank you.

I found a codily bug? so I report it.

* Wrong Case

I used codily to set the `domain`.
`domain` has been added not changed, when I changed `domain` and execute `codily --apply --file ./hoge.rb` (not specified dry-run or apply option)

* Sample Code
```

$domain_names=[
  'aaa.hoge.com',
  'bbb.hoge.com',
  'ccc.hoge.com',
-  'ddd.hoge.com'   <--- modifyed from
+  'eee.hoge.com'   <--- modifyed to
]

service "#{service_name}" do
  # Domain Seting
  $domain_names.each { |domain_name|
    domain "#{domain_name}"
  }
  ... ...

end
```

* unexpected diff
```
 domains:
 - name: aaa.hoge.com
   comment: ''
 - name: bbb.hoge.com
   comment: ''
+- name: eee.hoge.com
+  comment: ''
 - name: ddd.hoge.com
   comment: ''
```

* Behavior to expect

```
 domains:
 - name: aaa.hoge.com
   comment: ''
 - name: bbb.hoge.com
   comment: ''
+- - name: eee.hoge.com
   comment: ''
```
